// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBffZgv4w9CHwUlK1o5l59IcsiJFvAyqjQ',
    appId: '1:1089792746236:web:f2c085d5a1477d432ded79',
    messagingSenderId: '1089792746236',
    projectId: 'easydel-4b919',
    authDomain: 'easydel-4b919.firebaseapp.com',
    storageBucket: 'easydel-4b919.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJzxAV07Mp-B3OpQmH1V7nIS4bVHwxt9I',
    appId: '1:1089792746236:android:2834be043649c9642ded79',
    messagingSenderId: '1089792746236',
    projectId: 'easydel-4b919',
    storageBucket: 'easydel-4b919.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANsHx6TZbHSCeQ3s-fO6eBvl-ANAFbIQE',
    appId: '1:1089792746236:ios:a0a508492de5f9f72ded79',
    messagingSenderId: '1089792746236',
    projectId: 'easydel-4b919',
    storageBucket: 'easydel-4b919.appspot.com',
    iosBundleId: 'com.example.osm.RunnerTests',
  );
}
